#!/bin/sh

APP_DIR="/opt/ai/app/cardnum"
FACE_APP_DIR="/opt/ai/app/yhfacelib"
GO_MULTINFER_DIR="/opt/ai/app/multinfer"
MULTINFER_DEMO_DIR="/opt/ai/app/multinfer/bin/demo"

LOG_PATH="/opt/ai/logs"

start_web() {
        uwsgi  -s /opt/ai/tmp/uwsgi_card.sock -C -M -p 2 -t 60 --limit-as 1024 -R 1000 --uid nobody --gid nobody \
               -d $LOG_PATH"/uwsgi_card.log" --pidfile /opt/ai/tmp/uwsgi_card.pid --pythonpath $APP_DIR
        uwsgi  -s /opt/ai/tmp/uwsgi_face.sock -C -M -p 2 -t 60 --limit-as 1024 -R 1000 --uid nobody --gid nobody \
               -d $LOG_PATH"/uwsgi_face.log" --pidfile /opt/ai/tmp/uwsgi_face.pid --pythonpath $FACE_APP_DIR

        uwsgi  -s /opt/ai/tmp/uwsgi_demo.sock -C -M -p 2 -t 60 --limit-as 1024 -R 1000 --uid nobody --gid nobody \
               -d $LOG_PATH"/uwsgi_demo.log" --pidfile /opt/ai/tmp/uwsgi_demo.pid --pythonpath $MULTINFER_DEMO_DIR

        nginx -c /opt/ai/nginx/nginx.conf
        return 0
}

start_back() {
        nohup python3 $APP_DIR"/daemon.pyc" $APP_DIR $LOG_PATH >> $LOG_PATH"/daemon.log"  &

        LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib nohup $GO_MULTINFER_DIR"/bin/multinfer" server 0 --yaml $GO_MULTINFER_DIR"/config/settings.yaml" >> $LOG_PATH"/multinfer_server_0.log" 2>&1 &
        LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib nohup $GO_MULTINFER_DIR"/bin/multinfer" http --yaml $GO_MULTINFER_DIR"/config/settings.yaml" >> $LOG_PATH"/multinfer_http.log" 2>&1 &

        return 0 
}

stop_web() {
        nginx -s quit -c /opt/ai/nginx/nginx.conf
        kill -9 `pgrep -f "uwsgi"`
        sleep 2
        kill -9 `pgrep -f "nginx -c /opt/ai/nginx/nginx.conf"`
        return 0
}

stop_back() {
        kill -9 `pgrep -f "daemon.py"`
        kill -9 `pgrep -f "dispatcher.py"`
        kill -9 `pgrep -f "multinfer"`
        return 0
}

status() {
        ps -f -C uwsgi -C nginx -C python3 -C multinfer
        return 0
}

reload() {
        nginx -s reload
        return 0
}

restart() {
        stop_web
        stop_back
        sleep 1
        start_web
        start_back
}


case "$1" in
    start)
        case "$2" in
          web)
                start_web
                RETVAL=$?
                ;;
          back)
                start_back
                RETVAL=$?
                ;;
          *)
                start_web
                start_back
                RETVAL=$?
                ;;
        esac
        ;;
    stop)
        case "$2" in
          web)
                stop_web
                RETVAL=$?
                ;;
          back)
                stop_back
                RETVAL=$?
                ;;
          *)
                stop_web
                stop_back
                RETVAL=$?
                ;;
        esac 
        ;;
    restart)
        restart
        RETVAL=$?
        ;;
    reload)
        reload
        RETVAL=$?
        ;;
    status)
        status
        RETVAL=$?
        ;;
    *)
        echo $"Usage: my_server {start|stop|restart} {web|back|all} | reload | status"
        RETVAL=2
        ;;
esac

exit $RETVAL
