#!/bin/sh


REDIS_PATH="/opt/ai/app/redis-5.0.8"
LOG_PATH="/opt/ai/tmp"


start() {
	$REDIS_PATH"/redis-server" $REDIS_PATH"/redis.conf"
    	return 0 
}

stop() {
	kill -9 `pgrep -f "redis-server 127.0.0.1:7480"`
	return 0
}

status() {
	ps -ef|grep redis 
    	return 0
}


case "$1" in
    start)
	start
	RETVAL=$?
	;;
    stop)
	stop
	RETVAL=$?
	;;
    status)
	status
	RETVAL=$?
	;;
    *)
	echo $"Usage: redis_server {start|stop|status}"
	RETVAL=2
	;;
esac

exit $RETVAL
